apiVersion: v1
kind: Service
metadata:
{{- if .Values.tableManager.service.annotations }}
  annotations:
{{ toYaml .Values.tableManager.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "cortex.tableManager.labels" . | nindent 4 }}
{{- if .Values.tableManager.service.labels }}
{{ toYaml .Values.tableManager.service.labels | indent 4 }}
{{- end }}
  name: {{ template "cortex.tableManager.fullname" . }}
spec:
  ports:
    - port: 80
  selector:
    {{- include "cortex.tableManager.matchLabels" . | nindent 4 }}
