{{- if and .Values.retrieval.enabled .Values.retrieval.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    {{- include "cortex.retrieval.labels" . | nindent 4 }}
  name: {{ template "cortex.retrieval.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "cortex.retrieval.labels" . | nindent 4 }}
  name: {{ template "cortex.retrieval.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "cortex.retrieval.labels" . | nindent 4 }}
  name: {{ template "cortex.retrieval.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cortex.retrieval.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cortex.retrieval.fullname" . }}
{{- end }}
