apiVersion: v1
kind: Service
metadata:
{{- if .Values.distributor.service.annotations }}
  annotations:
{{ toYaml .Values.distributor.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "cortex.distributor.labels" . | nindent 4 }}
{{- if .Values.distributor.service.labels }}
{{ toYaml .Values.distributor.service.labels | indent 4 }}
{{- end }}
  name: {{ template "cortex.distributor.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.distributor.service.port }}
      targetPort: http
  selector:
    {{- include "cortex.distributor.matchLabels" . | nindent 4 }}
