apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    {{- include "cortex.configs.labels" . | nindent 4 }}
  name: {{ template "cortex.configs.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.configs.matchLabels" . | nindent 6 }}
  replicas: 1
  {{- if .Values.configs.strategy }}
  strategy:
{{ toYaml .Values.configs.strategy | indent 4 }}
  {{- end }}
  template:
    metadata:
    {{- if .Values.configs.podAnnotations }}
      annotations:
{{ toYaml .Values.configs.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "cortex.configs.labels" . | nindent 8 }}
    spec:
{{- if .Values.configs.schedulerName }}
      schedulerName: "{{ .Values.configs.schedulerName }}"
{{- end }}
{{- if .Values.configs.priorityClassName }}
      priorityClassName: "{{ .Values.configs.priorityClassName }}"
{{- end }}
      containers:
        - name: {{ template "cortex.name" . }}-{{ .Values.configs.name }}
          image: "{{ .Values.configs.image.repository }}:{{ tpl .Values.configs.image.tag . }}"
          imagePullPolicy: {{ .Values.configs.image.pullPolicy }}
          args:
            - -server.http-listen-port={{ .Values.configs.service.port }}
            - -database.uri=postgres://postgres@{{ template "cortex.configsDb.fullname" . }}.{{ .Release.Namespace }}/configs?sslmode=disable
            - -database.migrations=/migrations
          ports:
            - name: http
              containerPort: {{ .Values.configs.service.port }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: http
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 1
          resources:
{{ toYaml .Values.configs.resources | indent 12 }}
{{- if .Values.configs.affinity }}
      affinity:
{{ toYaml .Values.configs.affinity | indent 8 }}
{{- end }}
    {{- if .Values.configs.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.configs.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.configs.securityContext }}
      securityContext:
{{ toYaml .Values.configs.securityContext | indent 8 }}
    {{- end }}
    {{- if .Values.configs.tolerations }}
      tolerations:
{{ toYaml .Values.configs.tolerations | indent 8 }}
    {{- end }}
