apiVersion: v1
kind: Service
metadata:
{{- if .Values.configs.service.annotations }}
  annotations:
{{ toYaml .Values.configs.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "cortex.configs.labels" . | nindent 4 }}
{{- if .Values.configs.service.labels }}
{{ toYaml .Values.configs.service.labels | indent 4 }}
{{- end }}
  name: {{ template "cortex.configs.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.configs.service.port }}
      targetPort: http
  selector:
    {{- include "cortex.configs.matchLabels" . | nindent 4 }}
