apiVersion: v1
kind: Service
metadata:
{{- if .Values.ingester.service.annotations }}
  annotations:
{{ toYaml .Values.ingester.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "cortex.ingester.labels" . | nindent 4 }}
{{- if .Values.ingester.service.labels }}
{{ toYaml .Values.ingester.service.labels | indent 4 }}
{{- end }}
  name: {{ template "cortex.ingester.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.ingester.service.port }}
      targetPort: http
  selector:
    {{- include "cortex.ingester.matchLabels" . | nindent 4 }}
