{{- if .Values.s3.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.s3.service.annotations }}
  annotations:
{{ toYaml .Values.s3.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "cortex.s3.labels" . | nindent 4 }}
{{- if .Values.s3.service.labels }}
{{ toYaml .Values.s3.service.labels | indent 4 }}
{{- end }}
  name: {{ template "cortex.s3.fullname" . }}
spec:
  ports:
    - port: {{ .Values.s3.service.port }}
  selector:
    {{- include "cortex.s3.matchLabels" . | nindent 4 }}
{{- end }}
