{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "cortex.nginx.labels" . | nindent 4 }}
  name: {{ template "cortex.nginx.fullname" . }}
data:
  nginx.conf: |-
    worker_processes  5;  ## Default: 1
    error_log  /dev/stderr debug;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;
      sendfile     on;
      tcp_nopush   on;
      resolver kube-dns.kube-system.svc.cluster.local;

      server { # simple reverse-proxy
        listen 80;
        proxy_set_header X-Scope-OrgID 0;

        location = /api/prom/push {
          proxy_pass      http://{{ template "cortex.distributor.fullname" . }}.{{ .Release.Namespace }}$request_uri;
        }

        location = /ring {
          proxy_pass      http://{{ template "cortex.distributor.fullname" . }}.{{ .Release.Namespace }}$request_uri;
        }
        location = /all_user_stats {
          proxy_pass      http://{{ template "cortex.distributor.fullname" . }}.{{ .Release.Namespace }}$request_uri;
        }

        location ~ /api/prom/.* {
          proxy_pass      http://{{ template "cortex.queryFrontend.fullname" . }}.{{ .Release.Namespace }}$request_uri;
        }
      }
    }
{{- end }}
