apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    {{- include "cortex.ruler.labels" . | nindent 4 }}
  name: {{ template "cortex.ruler.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.ruler.matchLabels" . | nindent 6 }}
  replicas: 1
  {{- if .Values.ruler.strategy }}
  strategy:
{{ toYaml .Values.ruler.strategy | indent 4 }}
  {{- end }}
  template:
    metadata:
    {{- if .Values.ruler.podAnnotations }}
      annotations:
{{ toYaml .Values.ruler.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "cortex.ruler.labels" . | nindent 8 }}
    spec:
{{- if .Values.ruler.schedulerName }}
      schedulerName: "{{ .Values.ruler.schedulerName }}"
{{- end }}
{{- if .Values.ruler.priorityClassName }}
      priorityClassName: "{{ .Values.ruler.priorityClassName }}"
{{- end }}
      containers:
        - name: {{ template "cortex.name" . }}-{{ .Values.ruler.name }}
          image: "{{ .Values.ruler.image.repository }}:{{ tpl .Values.ruler.image.tag . }}"
          imagePullPolicy: {{ .Values.ruler.image.pullPolicy }}
          args:
            - -log.level=debug
            - -server.http-listen-port={{ .Values.ruler.service.port }}
            - -ruler.configs.url=http://{{ template "cortex.configs.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.configs.service.port }}
            - -ruler.alertmanager-url=http://{{ template "cortex.alertmanager.fullname" . }}.{{ .Release.Namespace }}/api/prom/alertmanager/
            - -consul.hostname={{ template "cortex.consul.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.consul.HttpPort }}
            - -s3.url=s3://abc:123@{{ template "cortex.s3.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.s3.service.port }}/s3
            - -dynamodb.original-table-name=cortex
            - -dynamodb.url=dynamodb://user:pass@{{ template "cortex.dynamodb.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.dynamodb.service.port }}
            - -dynamodb.periodic-table.prefix=cortex_weekly_
            - -dynamodb.periodic-table.from=2017-01-06
            - -dynamodb.daily-buckets-from=2017-01-10
            - -dynamodb.base64-buckets-from=2017-01-17
            - -dynamodb.v4-schema-from=2017-02-05
            - -dynamodb.v5-schema-from=2017-02-22
            - -dynamodb.v6-schema-from=2017-03-19
            - -dynamodb.chunk-table.from=2017-04-17
            - -memcached.hostname={{ template "cortex.memcached.fullname" . }}.{{ .Release.Namespace }}
            - -memcached.timeout=100ms
            - -memcached.service=memcached
            - -distributor.replication-factor=1
          ports:
            - name: http
              containerPort: {{ .Values.ruler.service.port }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: http
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 1
          resources:
{{ toYaml .Values.ruler.resources | indent 12 }}
{{- if .Values.ruler.affinity }}
      affinity:
{{ toYaml .Values.ruler.affinity | indent 8 }}
{{- end }}
    {{- if .Values.ruler.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.ruler.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.ruler.securityContext }}
      securityContext:
{{ toYaml .Values.ruler.securityContext | indent 8 }}
    {{- end }}
    {{- if .Values.ruler.tolerations }}
      tolerations:
{{ toYaml .Values.ruler.tolerations | indent 8 }}
    {{- end }}
